var myCache = require('../cache')
var parser = require('xml2json')

//race 3: no results, but odds = active
//race 2: no results, no odds = upcoming
//race 1: results = recent


exports.getTestData = function() {

  var testRaces = [{RaceNum: 1, PostTime: "2017-04-17T09:45:00-07:00"}, {RaceNum: 2, PostTime: "2017-04-18T23:02:00-07:00"}, {RaceNum: 3, PostTime: "2017-04-19T23:02:00-07:00"}]
  myCache.cache.put(myCache.cacheKeys.ALLRACES, testRaces)

  var testOdds3 = "<OddsResponse><RaceNum>3</RaceNum><MinutesToPost>0</MinutesToPost><WinOdds><Entries><Entry><ProgramNumber>101</ProgramNumber><TextOdds>8/5</TextOdds></Entry><Entry><ProgramNumber>2</ProgramNumber><TextOdds> 3/1</TextOdds></Entry><Entry><ProgramNumber>3</ProgramNumber><TextOdds> 11/1</TextOdds></Entry><Entry><ProgramNumber>4</ProgramNumber><TextOdds> 24/1</TextOdds></Entry><Entry><ProgramNumber>5</ProgramNumber><TextOdds> 34/1</TextOdds></Entry><Entry><ProgramNumber>6</ProgramNumber><TextOdds> 42/1</TextOdds></Entry><Entry><ProgramNumber>7</ProgramNumber><TextOdds> 5/2</TextOdds></Entry><Entry><ProgramNumber>8</ProgramNumber><TextOdds> 49/1</TextOdds></Entry><Entry><ProgramNumber>9</ProgramNumber><TextOdds> 6/1</TextOdds></Entry></Entries></WinOdds></OddsResponse>"
  myCache.cache.put(myCache.cacheKeys.ODDS + "3", parser.toJson(testOdds3, {object:true}))

  var testOdds2 = "<OddsResponse><RaceNum>8</RaceNum><MinutesToPost>99</MinutesToPost><WinOdds><Entries></Entries></WinOdds></OddsResponse>"
  myCache.cache.put(myCache.cacheKeys.ODDS + "2", parser.toJson(testOdds2, {object:true}))

  var testOdds1 = "<OddsResponse><RaceNum>8</RaceNum><MinutesToPost>99</MinutesToPost><WinOdds><Entries></Entries></WinOdds></OddsResponse>"
  myCache.cache.put(myCache.cacheKeys.ODDS + "1", parser.toJson(testOdds1, {object:true}))

  var testEntries = {
  RaceNum: 1,
  Entries: [
  {
  ProgramNumber: "1",
  PostPosition: 9,
  HorseName: "Clever Trevor",
  ML: "15/1",
  Jockey: "Bradley, Ira J.",
  Weight: "119 Lbs",
  Trainer: "Childers, Gary",
  Medication: "L",
  MedWeight: 119,
  Sire: "PETIONVILLE",
  Dam: "SO EMOTIONAL",
  Color: "CH",
  Age: 7,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "FLORENCE M KNIGHT",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "1A",
  PostPosition: 10,
  HorseName: "AlwaysABaddy",
  ML: "9/2",
  Jockey: "15/1",
  Weight: "119 Lbs",
  Trainer: "Childers, Gary",
  Medication: "L",
  MedWeight: 119,
  Sire: "BADDY DADDY",
  Dam: "ALWAYSASTUNNER",
  Color: "B",
  Age: 8,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "FLORENCE M KNIGHT",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "2",
  PostPosition: 1,
  HorseName: "Sister Mary Sary",
  ML: "9/2",
  Jockey: "Thomas, Megan D.",
  Weight: "119 Lbs",
  Trainer: "Lamar L. Walters",
  Medication: "L",
  MedWeight: 119,
  Sire: "LEMON DROP KID",
  Dam: "PLEASANT MATE",
  Color: "DKBR",
  Age: 8,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "SOCORRO D. LINDNER",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "3",
  PostPosition: 2,
  HorseName: "Mr Garde",
  ML: "15/1",
  Jockey: "Tedesco, Reyna B.",
  Weight: "119 Lbs",
  Trainer: "Karen K. Brown",
  Medication: "L",
  MedWeight: 119,
  Sire: "JAZIL",
  Dam: "SONG OF CONFIDENCE",
  Color: "CH",
  Age: 5,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "KAREN BROWN",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "4",
  PostPosition: 3,
  HorseName: "Corinthians Secret",
  ML: "7/2",
  Jockey: "Anderson, Quinton L.",
  Weight: "119 Lbs",
  Trainer: "Brenda G Smith",
  Medication: "L",
  MedWeight: 119,
  Sire: "CORINTHIAN",
  Dam: "DREAM LUCK",
  Color: "GR/RO",
  Age: 4,
  Sex: "G",
  BreedingLocation: "IL",
  Owner: "Marie V Sandoval",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "5",
  PostPosition: 4,
  HorseName: "Aish Tamid",
  ML: "10/1",
  Jockey: "Elizabeth S. Lucas",
  Weight: "119 Lbs",
  Trainer: "Margaret R. Baumgardner",
  Medication: "L",
  MedWeight: 119,
  Sire: "PURIM",
  Dam: "FIRST LIGHT",
  Color: "B",
  Age: 5,
  Sex: "G",
  BreedingLocation: "ON",
  Owner: "ERIC T KNAPP",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "6",
  PostPosition: 5,
  HorseName: "Chicot Bay",
  ML: "15/1",
  Jockey: "Williams, Kathryn L.",
  Weight: "116 Lbs",
  Trainer: "Arias, Frank K.",
  Medication: "L",
  MedWeight: 116,
  Sire: "DOCTOR MIKE",
  Dam: "MY SUNSHINE",
  Color: "B",
  Age: 6,
  Sex: "G",
  BreedingLocation: "LA",
  Owner: "TODD S. ALVARADO",
  ClaimingPrice: 0
  },
  {
  ProgramNumber: "7",
  PostPosition: 6,
  HorseName: "Sunwave",
  ML: "8/1",
  Jockey: "Adams, Richard A.",
  Weight: "116 Lbs",
  Trainer: "Banks, Homer T.",
  Medication: "L",
  MedWeight: 116,
  Sire: "SUN KING",
  Dam: "HUMBOLDT BELLE",
  Color: "CH",
  Age: 5,
  Sex: "G",
  BreedingLocation: "LA",
  Owner: "HAGGAMAN &amp; ASSOCIATES, INC",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "8",
  PostPosition: 7,
  HorseName: "Calipari's Kitten",
  ML: "3/1",
  Jockey: "Na, Inez D.",
  Weight: "119 Lbs",
  Trainer: "Roper, Dorothy G.",
  Medication: "L",
  MedWeight: 119,
  Sire: "KITTEN'S JOY",
  Dam: "MISS BERGDORF",
  Color: "B",
  Age: 7,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "MARY W. PETERSEN",
  ClaimingPrice: 5000
  },
  {
  ProgramNumber: "9",
  PostPosition: 8,
  HorseName: "Chad Be Glad",
  ML: "4/1",
  Jockey: "Padroza, Marcelino",
  Weight: "116 Lbs",
  Trainer: "Gibson, Jonas",
  Medication: "L",
  MedWeight: 119,
  Sire: "GLAD TIDINGS",
  Dam: "CHADDES",
  Color: "CH",
  Age: 7,
  Sex: "C",
  BreedingLocation: "KY",
  Owner: "ROBT B EVANOFF",
  ClaimingPrice: 5000
  }
  ]
  }
  myCache.cache.put(myCache.cacheKeys.ONEENTRY + "1", testEntries)

  var testEntries2 = {
  RaceNum: 2,
  Entries: [
  {
  ProgramNumber: "100",
  PostPosition: 9,
  HorseName: "Clever Trevor",
  Jockey: "Bradley, Ira J.",
  Weight: "119 Lbs",
  Trainer: "Childers, Gary",
  Medication: "L",
  MedWeight: 119,
  Sire: "PETIONVILLE",
  Dam: "SO EMOTIONAL",
  Color: "CH",
  Age: 7,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "FLORENCE M KNIGHT",
  ClaimingPrice: 5000
  }
  ]
  }
  myCache.cache.put(myCache.cacheKeys.ONEENTRY + "2", testEntries2)

  var testEntries3 = {
  RaceNum: 3,
  Entries: [
  {
  ProgramNumber: "101",
  PostPosition: 9,
  HorseName: "Clever Trevor",
  ML : "23/1",
  Jockey: "Bradley, Ira J.",
  Weight: "119 Lbs",
  Trainer: "Childers, Gary",
  Medication: "L",
  MedWeight: 119,
  Sire: "PETIONVILLE",
  Dam: "SO EMOTIONAL",
  Color: "CH",
  Age: 7,
  Sex: "G",
  BreedingLocation: "KY",
  Owner: "FLORENCE M KNIGHT",
  ClaimingPrice: 5000
  }
  ]
  }
  myCache.cache.put(myCache.cacheKeys.ONEENTRY + "3", testEntries3)

  var testResults3 = "<ResultsResponse><RaceNum>2</RaceNum><Entries></Entries><Message>Results not ready.</Message></ResultsResponse>"
  myCache.cache.put(myCache.cacheKeys.ONERESULT + "3", parser.toJson(testResults3, {object:true}))

  var testResults2 = "<ResultsResponse><RaceNum>2</RaceNum><Entries></Entries><Message>Results not ready.</Message></ResultsResponse>"
  myCache.cache.put(myCache.cacheKeys.ONERESULT + "2", parser.toJson(testResults2, {object:true}))

  var testResults1 = "<ResultsResponse><RaceNum>1</RaceNum><Entries><Entry><ProgramNumber>5</ProgramNumber><Pools><Pool><PoolType>WN</PoolType><Base>1</Base><Value>2.4</Value></Pool><Pool><PoolType>PL</PoolType><Base>1</Base><Value>3.5</Value></Pool><Pool><PoolType>SH</PoolType><Base>1</Base><Value>4.5</Value></Pool></Pools></Entry><Entry><ProgramNumber>2</ProgramNumber><Pools><Pool><PoolType>PL</PoolType><Base>1</Base><Value>5.63</Value></Pool><Pool><PoolType>SH</PoolType><Base>1</Base><Value>4.11</Value></Pool></Pools></Entry><Entry><ProgramNumber>1</ProgramNumber><Pools><Pool><PoolType>SH</PoolType><Base>1</Base><Value>3.45</Value></Pool></Pools></Entry></Entries></ResultsResponse>"
  myCache.cache.put(myCache.cacheKeys.ONERESULT + "1", parser.toJson(testResults1, {object:true}))


}

exports.testobject = {
"activeRaces": [
{
"id": 2,
"postTime": "2017-04-19T11:45:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000,
"odds": "9/2"
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000,
"odds": "5/1"
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000,
"odds": "18/1"
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000,
"odds": "SCR"
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000,
"odds": "5/1"
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0,
"odds": "3/1"
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000,
"odds": "12/1"
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000,
"odds": "22/1"
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000,
"odds": "11/1"
}
],
"hasOdds": true,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 3,
"postTime": "2017-04-19T12:25:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 4,
"postTime": "2017-04-19T12:55:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 5,
"postTime": "2017-04-19T14:27:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 6,
"postTime": "2017-04-19T17:23:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 7,
"postTime": "2017-04-19T19:12:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
},
{
"id": 8,
"postTime": "2017-04-19T23:02:00-07:00",
"hasResults": false,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000
}
],
"hasOdds": false,
"hasML": true,
"results": {
"WN": [],
"PL": [],
"SH": []
}
}
],
"upcomingRaces": [],
"recentRaces": [
{
"id": 1,
"postTime": "2017-04-19T09:45:00-07:00",
"hasResults": true,
"entries": [
{
"ProgramNumber": "1",
"PostPosition": 9,
"HorseName": "Clever Trevor",
"ML": "15/1",
"Jockey": "Bradley, Ira J.",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "PETIONVILLE",
"Dam": "SO EMOTIONAL",
"Color": "CH",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000,
"odds": "8/5",
"result": {
"PoolType": "SH",
"Base": "1",
"Value": "3.45"
}
},
{
"ProgramNumber": "1A",
"PostPosition": 10,
"HorseName": "AlwaysABaddy",
"ML": "9/2",
"Jockey": "15/1",
"Weight": "119 Lbs",
"Trainer": "Childers, Gary",
"Medication": "L",
"MedWeight": 119,
"Sire": "BADDY DADDY",
"Dam": "ALWAYSASTUNNER",
"Color": "B",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "FLORENCE M KNIGHT",
"ClaimingPrice": 5000
},
{
"ProgramNumber": "2",
"PostPosition": 1,
"HorseName": "Sister Mary Sary",
"ML": "9/2",
"Jockey": "Thomas, Megan D.",
"Weight": "119 Lbs",
"Trainer": "Lamar L. Walters",
"Medication": "L",
"MedWeight": 119,
"Sire": "LEMON DROP KID",
"Dam": "PLEASANT MATE",
"Color": "DKBR",
"Age": 8,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "SOCORRO D. LINDNER",
"ClaimingPrice": 5000,
"odds": "3/1",
"result": [
{
"PoolType": "PL",
"Base": "1",
"Value": "5.63"
},
{
"PoolType": "SH",
"Base": "1",
"Value": "4.11"
}
]
},
{
"ProgramNumber": "3",
"PostPosition": 2,
"HorseName": "Mr Garde",
"ML": "15/1",
"Jockey": "Tedesco, Reyna B.",
"Weight": "119 Lbs",
"Trainer": "Karen K. Brown",
"Medication": "L",
"MedWeight": 119,
"Sire": "JAZIL",
"Dam": "SONG OF CONFIDENCE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "KAREN BROWN",
"ClaimingPrice": 5000,
"odds": "11/1"
},
{
"ProgramNumber": "4",
"PostPosition": 3,
"HorseName": "Corinthians Secret",
"ML": "7/2",
"Jockey": "Anderson, Quinton L.",
"Weight": "119 Lbs",
"Trainer": "Brenda G Smith",
"Medication": "L",
"MedWeight": 119,
"Sire": "CORINTHIAN",
"Dam": "DREAM LUCK",
"Color": "GR/RO",
"Age": 4,
"Sex": "G",
"BreedingLocation": "IL",
"Owner": "Marie V Sandoval",
"ClaimingPrice": 5000,
"odds": "24/1"
},
{
"ProgramNumber": "5",
"PostPosition": 4,
"HorseName": "Aish Tamid",
"ML": "10/1",
"Jockey": "Elizabeth S. Lucas",
"Weight": "119 Lbs",
"Trainer": "Margaret R. Baumgardner",
"Medication": "L",
"MedWeight": 119,
"Sire": "PURIM",
"Dam": "FIRST LIGHT",
"Color": "B",
"Age": 5,
"Sex": "G",
"BreedingLocation": "ON",
"Owner": "ERIC T KNAPP",
"ClaimingPrice": 5000,
"odds": "34/1",
"result": [
{
"PoolType": "WN",
"Base": "1",
"Value": "2.4"
},
{
"PoolType": "PL",
"Base": "1",
"Value": "3.5"
},
{
"PoolType": "SH",
"Base": "1",
"Value": "4.5"
}
]
},
{
"ProgramNumber": "6",
"PostPosition": 5,
"HorseName": "Chicot Bay",
"ML": "15/1",
"Jockey": "Williams, Kathryn L.",
"Weight": "116 Lbs",
"Trainer": "Arias, Frank K.",
"Medication": "L",
"MedWeight": 116,
"Sire": "DOCTOR MIKE",
"Dam": "MY SUNSHINE",
"Color": "B",
"Age": 6,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "TODD S. ALVARADO",
"ClaimingPrice": 0,
"odds": "42/1"
},
{
"ProgramNumber": "7",
"PostPosition": 6,
"HorseName": "Sunwave",
"ML": "8/1",
"Jockey": "Adams, Richard A.",
"Weight": "116 Lbs",
"Trainer": "Banks, Homer T.",
"Medication": "L",
"MedWeight": 116,
"Sire": "SUN KING",
"Dam": "HUMBOLDT BELLE",
"Color": "CH",
"Age": 5,
"Sex": "G",
"BreedingLocation": "LA",
"Owner": "HAGGAMAN &amp; ASSOCIATES, INC",
"ClaimingPrice": 5000,
"odds": "5/2"
},
{
"ProgramNumber": "8",
"PostPosition": 7,
"HorseName": "Calipari's Kitten",
"ML": "3/1",
"Jockey": "Na, Inez D.",
"Weight": "119 Lbs",
"Trainer": "Roper, Dorothy G.",
"Medication": "L",
"MedWeight": 119,
"Sire": "KITTEN'S JOY",
"Dam": "MISS BERGDORF",
"Color": "B",
"Age": 7,
"Sex": "G",
"BreedingLocation": "KY",
"Owner": "MARY W. PETERSEN",
"ClaimingPrice": 5000,
"odds": "49/1"
},
{
"ProgramNumber": "9",
"PostPosition": 8,
"HorseName": "Chad Be Glad",
"ML": "4/1",
"Jockey": "Padroza, Marcelino",
"Weight": "116 Lbs",
"Trainer": "Gibson, Jonas",
"Medication": "L",
"MedWeight": 119,
"Sire": "GLAD TIDINGS",
"Dam": "CHADDES",
"Color": "CH",
"Age": 7,
"Sex": "C",
"BreedingLocation": "KY",
"Owner": "ROBT B EVANOFF",
"ClaimingPrice": 5000,
"odds": "6/1"
}
],
"hasOdds": true,
"hasML": true,
"results": {
"WN": [
5
],
"PL": [
2
],
"SH": [
1
]
}
}
]
}
